#!/bin/bash

export NO_GAIL=0
export NO_AT_BRIDGE=0

dbus-test-runner --dbus-config /usr/share/dbus-test-runner/session.conf --task ../test-gtk-label-client --task-name Client --task ../test-gtk-label-server --parameter ./$1 --task-name Server --ignore-return


