debian/tmp/gtk3/usr/include/libdbusmenu-0.4/libdbusmenu-gtk3 /usr/include/libdbusmenu-0.4/
debian/tmp/gtk3/usr/lib/pkgconfig/dbusmenu-gtk3-0.4.pc /usr/lib/pkgconfig/
debian/tmp/gtk3/usr/lib/libdbusmenu-gtk3.a /usr/lib/
debian/tmp/gtk3/usr/lib/libdbusmenu-gtk3.so /usr/lib/
debian/tmp/gtk3/usr/share/gir-1.0/DbusmenuGtk3-0.4.gir /usr/share/gir-1.0/
debian/tmp/gtk3/usr/share/vala/vapi/DbusmenuGtk3-0.4.vapi /usr/share/gir-1.0/
