debian/tmp/gtk2/usr/include/libdbusmenu-0.4/libdbusmenu-gtk /usr/include/libdbusmenu-0.4/
debian/tmp/gtk2/usr/lib/pkgconfig/dbusmenu-gtk-0.4.pc /usr/lib/pkgconfig/
debian/tmp/gtk2/usr/lib/libdbusmenu-gtk.a /usr/lib/
debian/tmp/gtk2/usr/lib/libdbusmenu-gtk.so /usr/lib/
debian/tmp/gtk2/usr/share/gir-1.0/DbusmenuGtk-0.4.gir /usr/share/gir-1.0/
debian/tmp/gtk2/usr/share/vala/vapi/DbusmenuGtk-0.4.vapi /usr/share/vala/vapi/
