debian/tmp/gtk3/usr/include/libdbusmenu-0.4/libdbusmenu-glib /usr/include/libdbusmenu-0.4/
debian/tmp/gtk3/usr/lib/pkgconfig/dbusmenu-glib-0.4.pc /usr/lib/pkgconfig/
debian/tmp/gtk3/usr/lib/libdbusmenu-glib.a /usr/lib/
debian/tmp/gtk3/usr/lib/libdbusmenu-glib.so /usr/lib/
debian/tmp/gtk3/usr/share/gir-1.0/Dbusmenu-0.4.gir /usr/share/gir-1.0/
debian/tmp/gtk3/usr/share/vala/vapi/Dbusmenu-0.4.vapi /usr/share/vala/vapi/
