const char * dbus_menu_clean_xml = 
"<?xml version=\"1.0\"?>\n"
"<node name=\"/\">\n"
"    \n"
"	<interface name=\"com.canonical.dbusmenu\">\n"
"		\n"
"\n"
"\n"
"		<property name=\"version\" type=\"u\" access=\"read\">\n"
"			\n"
"		</property>\n"
"\n"
"\n"
"\n"
"		<method name=\"GetLayout\">\n"
"			\n"
"			<arg type=\"i\" name=\"parentId\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"			<arg type=\"u\" name=\"revision\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"			<arg type=\"s\" name=\"layout\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"		</method>\n"
"\n"
"		<method name=\"GetGroupProperties\">\n"
"			<annotation name=\"com.trolltech.QtDBus.QtTypeName.In0\" value=\"QVariantList\"/>\n"
"			<annotation name=\"com.trolltech.QtDBus.QtTypeName.Out0\" value=\"DBusMenuItemList\"/>\n"
"			\n"
"			<arg type=\"ai\" name=\"ids\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"			<arg type=\"as\" name=\"propertyNames\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"			<arg type=\"a(ia{sv})\" name=\"properties\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"		</method>\n"
"\n"
"		<method name=\"GetChildren\">\n"
"			<annotation name=\"com.trolltech.QtDBus.QtTypeName.Out0\" value=\"DBusMenuItemList\"/>\n"
"			<arg type=\"i\" name=\"id\" direction=\"in\"/>\n"
"			<arg type=\"as\" name=\"propertyNames\" direction=\"in\"/>\n"
"			<arg type=\"a(ia{sv})\" name=\"properties\" direction=\"out\"/>\n"
"		</method>\n"
"\n"
"		<method name=\"GetProperty\">\n"
"			<arg type=\"i\" name=\"id\" direction=\"in\"/>\n"
"			<arg type=\"s\" name=\"name\" direction=\"in\"/>\n"
"			<arg type=\"v\" name=\"value\" direction=\"out\"/>\n"
"		</method>\n"
"\n"
"		<method name=\"GetProperties\">\n"
"			\n"
"			<annotation name=\"com.trolltech.QtDBus.QtTypeName.Out0\" value=\"QVariantMap\"/>\n"
"			<arg type=\"i\" name=\"id\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"			<arg type=\"as\" name=\"propertyNames\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"			<arg type=\"a{sv}\" name=\"properties\" direction=\"out\"/>\n"
"		</method>\n"
"\n"
"		<method name=\"Event\">\n"
"			\n"
"			<arg type=\"i\" name=\"id\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"			<arg type=\"s\" name=\"eventId\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"			<arg type=\"v\" name=\"data\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"			<arg type=\"u\" name=\"timestamp\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"		</method>\n"
"\n"
"		<method name=\"AboutToShow\">\n"
"			\n"
"			<arg type=\"i\" name=\"id\" direction=\"in\">\n"
"				\n"
"			</arg>\n"
"			<arg type=\"b\" name=\"needUpdate\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"		</method>\n"
"\n"
"\n"
"		<signal name=\"ItemPropertyUpdated\">\n"
"			\n"
"			<arg type=\"i\" name=\"id\" direction=\"out\"/>\n"
"			<arg type=\"s\" name=\"prop\" direction=\"out\"/>\n"
"			<arg type=\"v\" name=\"value\" direction=\"out\"/>\n"
"		</signal>\n"
"\n"
"		<signal name=\"ItemUpdated\">\n"
"			\n"
"			<arg type=\"i\" name=\"id\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"		</signal>\n"
"\n"
"		<signal name=\"LayoutUpdated\">\n"
"			\n"
"			<arg type=\"u\" name=\"revision\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"			<arg type=\"i\" name=\"parent\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"		</signal>\n"
"		<signal name=\"ItemActivationRequested\">\n"
"			\n"
"			<arg type=\"i\" name=\"id\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"			<arg type=\"u\" name=\"timestamp\" direction=\"out\">\n"
"				\n"
"			</arg>\n"
"		</signal>\n"
"\n"
"\n"
"\n"
"	</interface>\n"
"</node>\n"
;
